name: applensys
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.0.0
  cupertino_icons: ^1.0.8
  uuid: ^4.3.1
  fl_chart: ^1.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.5.0
  responsive_framework: ^1.5.1
  flutter_slidable: ^4.0.0
  flutter_local_notifications: ^19.3.1
  timezone: ^0.10.1
  path: ^1.8.3
  meta: ^1.16.0
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.5
  get_it: ^8.0.3
  flutter_riverpod: ^2.6.1
  flutter_localizations:
    sdk: flutter
  file_picker: ^10.2.0
  share_plus: ^11.0.0
  cross_file: ^0.3.4+2
  http: ^1.4.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  permission_handler: ^12.0.0+1
  pdf: ^3.10.8
  printing: ^5.12.0
  screenshot: ^3.0.0
  provider: ^6.1.5
  fluentui_system_icons: ^1.1.273
  file_selector: ^1.0.3
  open_file: ^3.5.10
  google_sign_in: ^7.1.1
  connectivity_plus: ^6.1.4
  googleapis: ^14.0.0
  mailer: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 
  pubspec_checker: ^1.0.9


flutter:
  uses-material-design: true
  assets:
    - assets/t1.json
    - assets/t2.json
    - assets/t3.json
    - assets/logo.webp
    - assets/shingomodel.webp
    - assets/logoblanco.webp
    - assets/portada.webp
    - assets/estructura_base.json
    - assets/report.json
